webtalk_init -webtalk_dir C:/Users/ashok/OneDrive/Documents/GitHub/FPGA_CNN_digit_recognition/src/project_dcnn/project_dcnn.sim/sim_1/behav/xsim/xsim.dir/tb_LeNet_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 19 23:17:38 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2f9066fb-de79-47a2-89e6-1681101a3f7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "829ff7320fe9405289591daecfc8d80e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2895 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "88 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7468_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2728765812 -regid "" -xml C:/Users/ashok/OneDrive/Documents/GitHub/FPGA_CNN_digit_recognition/src/project_dcnn/project_dcnn.sim/sim_1/behav/xsim/xsim.dir/tb_LeNet_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ashok/OneDrive/Documents/GitHub/FPGA_CNN_digit_recognition/src/project_dcnn/project_dcnn.sim/sim_1/behav/xsim/xsim.dir/tb_LeNet_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ashok/OneDrive/Documents/GitHub/FPGA_CNN_digit_recognition/src/project_dcnn/project_dcnn.sim/sim_1/behav/xsim/xsim.dir/tb_LeNet_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
